on:
  push:
    branches:
      - main
  schedule:
    - cron: "15 11,23 * * *"

jobs:
  sync:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - run: terraform init
      - run: terraform apply -auto-approve
        env:
          TF_VAR_RCLONE_CONFIG_PASS: ${{ secrets.TF_VAR_RCLONE_CONFIG_PASS }}
          TF_VAR_VULTR_API_KEY: ${{ secrets.TF_VAR_VULTR_API_KEY }}

