on:
  push:
    branches:
      - main
  schedule:
    - cron: "15 11,23 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - run: terraform apply -auto-approve
